# MineChat - Chat to players on Minecraft, using external apps!

# The port to listen on.
# Default: 25575
port: 25575

# The time in minutes before a link code expires.
# Default: 5
expiry-code-minutes: 5

# TLS settings for the server.
tls:
  # Enable or disable TLS.
  # If enabled, you must provide a keystore.
  enabled: false
  # The name of the keystore file in the plugin's data folder.
  keystore: "keystore.jks"
  # The password for the keystore.
  keystore-password: "password"
