name: ${NAME}
version: ${VERSION}
main: ${PACKAGE}.MineChatPlugin
description: MineChat Server
author: winlogon
website: https://github.com/MineChatPowered/server
api-version: '1.21'
folia-supported: true
loader: ${PACKAGE}.MineChatLoader
